# Generated by Django 3.0.4 on 2020-04-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='', upload_to='', verbose_name='Avatar'),
            preserve_default=False,
        ),
    ]
