# Generated by Django 3.0.5 on 2020-04-04 15:44

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(upload_to=main.models.tmp, verbose_name='Avatar'),
        ),
    ]
