# Generated by Django 3.0.5 on 2020-04-10 18:05

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200404_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='', upload_to=main.models.tmp),
            preserve_default=False,
        ),
    ]
