# Generated by Django 3.0.5 on 2020-04-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_emailset_passw'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailset',
            name='old_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
